Add line numbers to Syntax Errors
ExtendLang/Extend pull request #11
Opened 2016-11-30 22:42 UTC by ishaankolluri

Adds a line count to scanner-level syntax errors.

2016-11-30 22:52 UTC, Neitsch requested changes
Please add a testcase WITH output to assert correctness.

2016-12-01 08:57 UTC, ishaankolluri commented
To do:
* still have to increment the characters in the `read_string` buffer. Slightly more tricky. Will play around with it tomorrow.
* build a variety of test cases to illustrate the usage in comments, single line comments, with `extern`, etc.

2016-12-01 20:06 UTC, ishaankolluri commented
Would love some feedback on correctness/best practice.

Also, would love some more ideas for interesting test cases here. Was thinking about testing `read_string`, but couldn't readily come up with an idea of how to break it.

2016-12-01 20:08 UTC, ishaankolluri commented
Example:

``plt4115@plt4115 ~/Extend (parse_error) $ ./main.byte -c testcases/inputs/test_parse_error_comment.xtnd
Fatal error: exception Scanner.SyntaxError("Invalid character: $ on line 3 at character 30")``

2016-12-01 22:02 UTC, Neitsch approved these changes
Please add a testcase that uses a string. For example
foo := "Hello"; $$$;

2016-12-01 22:02 UTC, Neitsch commented on src/main/parser.mly
> +  flush stdout*)
Remove comment.

2016-12-01 23:56 UTC, ishaankolluri commented on src/main/parser.mly
> +  flush stdout*)
Sorry about this!

2016-12-01 23:58 UTC, oracleofnj commented
cool!

2016-12-01 23:59 UTC, merged